title: Welcome to&nbsp;our coffee&nbsp;table!
logo: /assets/img/logo.png
description: This is your guide to a more beautiful neural network design. Get your copy now!
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
